# Generated by Django 4.0.6 on 2022-07-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth',
        ),
    ]
